import { GoogleGenAI } from "@google/genai";

// Helper to convert File to Base64
const fileToPart = async (file: File): Promise<{ inlineData: { data: string; mimeType: string } }> => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onloadend = () => {
      if (typeof reader.result === 'string') {
        // Remove the data URL prefix (e.g., "data:image/jpeg;base64,")
        const base64Data = reader.result.split(',')[1];
        resolve({
          inlineData: {
            data: base64Data,
            mimeType: file.type,
          },
        });
      } else {
        reject(new Error('Failed to read file'));
      }
    };
    reader.onerror = reject;
    reader.readAsDataURL(file);
  });
};

export const generateRoomWithRug = async (sceneImage: File, rugImage: File): Promise<string> => {
  try {
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

    const scenePart = await fileToPart(sceneImage);
    const rugPart = await fileToPart(rugImage);

    // Prompt engineering to guide the model to perform the specific image editing task
    const prompt = `
      Instructions:
      1. You are an expert interior design AI.
      2. The first image provided is a 'Scene' (e.g., a living room with a sofa).
      3. The second image provided is a 'Rug' (pattern/texture).
      4. Your task is to generate a HIGH REALISM photo of the 'Scene' but replace the existing floor covering or rug with the design from the 'Rug' image.
      5. Strictly maintain the perspective, lighting, shadows, and furniture placement of the original Scene.
      6. The new rug must look like it is physically on the floor, correctly tucked under the sofa or furniture if applicable.
      7. Return ONLY the generated image.
    `;

    // Using gemini-2.5-flash-image for image generation tasks
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          scenePart, // Part 0
          rugPart,   // Part 1
          { text: prompt }
        ],
      },
    });

    // Iterate through parts to find the image
    const candidates = response.candidates;
    if (candidates && candidates.length > 0) {
      const parts = candidates[0].content.parts;
      for (const part of parts) {
        if (part.inlineData) {
          return `data:image/png;base64,${part.inlineData.data}`;
        }
      }
    }

    throw new Error("No image generated by the model.");
  } catch (error) {
    console.error("Gemini API Error:", error);
    throw error;
  }
};